aiidalab/aiidalab-launch

- aiidalab_launch/__main__.py
Sending an exec command to the container can sometimes be a blocking
process with non insignificant wait time.
> Show progress indicator while creating exec.

- aiidalab_launch/__main__.py
- aiidalab_launch/core.py
- tests/test_cli.py
- tests/test_core.py
Since the profile name is used as basis for the docker container name it
must be restricted to values valid for containers names. While that
definition might change, the conservative restrictions imposed with this
change set should protect us against any surprises in that regard for
now.
In addition, we do not allow underscores since this might interefere
with the ability to change the tool implementation to use docker-compose
in the future.
Fixes #36.
> Restrict valid profile names and implement associated unit tests.

- aiidalab_launch/util.py
One type of timeout error was not sufficiently caught.
> Fix: Handle error which can occur during check for update.

- aiidalab_launch/__main__.py
- aiidalab_launch/core.py
- tests/test_core.py
Relevant for when the host port is determined dynamically (e.g. by
setting it to 0 or None).
> Fix: Correctly Distinguish been configured and actually used host port.

- aiidalab_launch/instance.py
That property is not always set, e.g., for locally tagged images.
> Fix: Do not use RepoDigests image attribute.

- aiidalab_launch/__main__.py
`-p` is already used to specify profile so it cannot be a shorthand for `--privileged`
> Remove conflicting option for exec command

- README.md
- aiidalab_launch/__main__.py
- aiidalab_launch/application_state.py
- aiidalab_launch/config.py
- aiidalab_launch/instance.py
- aiidalab_launch/profile.py
- aiidalab_launch/util.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_instance.py
- tests/test_profile.py
Closes #130 
This needs tests and probably more error handling, but I'd like to have some eyes on this early to confirm if I am on the right track here.
CC @csadorf
> Feature: extra mounts

- aiidalab_launch/__main__.py
- aiidalab_launch/instance.py
Basic aiidalab container comes with HTTP, but users might want to add HTTPS.
Here we just modify the code that tries to connect to Jupyter Notebook to determine whether it is ready.
I am currently playing with HTTPS for local development in our Docker image built on top of AiiDAlab-docker-stack, see https://github.com/danielhollas/aiidalab-ispg-docker-stack/pull/6 if that is of interest.
**TODO**:
> Support HTTPS connection to Jupyter notebook

- aiidalab_launch/__main__.py
- tests/test_cli.py
Closes #135 
```sh
$ aiidalab-launch profiles edit invalid
Unexpected ValueError: Did not find profile with name 'invalid'.
Use verbose mode `aiidalab-launch --verbose` to see full stacktrace
```
I tried adding a test, but unfortunately the custom handler path is not exercised (see Codecov). Not very surprising that testing a custom exception handler in a testing framework does not work. :shrug: 
@csadorf this is ready for review.
> Hide stacktrace unless verbose mode is enabled

- .github/workflows/ci.yml
- aiidalab_launch/instance.py
- aiidalab_launch/profile.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_instance.py
> Support aiidalab/full-stack

- aiidalab_launch/__main__.py
- aiidalab_launch/instance.py
- tests/test_instance.py
Only emit a warning if Docker image is not found on Dockerhub.
This is useful for Docker images built locally, so that we do not always have to type "--no-pull"
when running `aiidalab-launch start`
Closes #153
I verifies locally that things still work as expected.
> Do not raise if Docker image cannot be pulled

- aiidalab_launch/__main__.py
- aiidalab_launch/util.py
- tests/test_cli.py
When verbose output is enabled via the `-v` option, the spinner interferes with the extra output.
Closes #146
> Don't show spinner with verbose output

- .github/workflows/ci.yml
- .gitignore
- aiidalab_launch/__main__.py
- aiidalab_launch/instance.py
I was trying to hunt down the issue behing the GHA CI timeout failures, reported in #163. 
The hypothesis was to see if issue #154 was behind this. See my last comment on #154 for details about my investigation. One think I noticed is that the asyncio `echo_logs` Task would not get cancelled if the container failed to start. I don't know if this is the reason for the test flakiness, but it is worth a shot I think.
EDIT: So this obviously did not help, but it still seems like a change worth doing. I've also decreased the timeout on GHA so that at least we're not wasting CI minutes.
> Trying to fix flaky test suite

- aiidalab_launch/profile.py
First of all, we have the plan to not provide aiidalab-widgets-base as an app in the future. And we don't have a production release version for aiidalab-widgets-base, which will install the old version that is incompatible with the full-stack image. 
I think it makes more sense not to provide aiidalab-widgets-base as the default app as the default profile setting. It will cause the issue that when user follow the aiidalab-launch [instruction](https://aiidalab.readthedocs.io/en/latest/usage/index.html#aiidalab-launch) to using aiidalab first time, they will getting a broken container.
> Setting default app list in profiles empty

- .pre-commit-config.yaml
Pre-commit CI build started failing recently. Updating `isort` should fix it, same fix was applied in the aiida-core repo, see https://github.com/aiidalab/aiidalab-launch/pull/new/ci/update-isort for details.
Same issue is likely present in other AiiDAlab repos.
> Update isort to fix pre-commit CI build

- .github/workflows/ci.yml
- aiidalab_launch/__main__.py
The `echo_logs` function prints out the logs from the container (i.e. the output of `aiidalab-launch logs`) while the user waits for the container to start. However, logs are printed with `logging.DEBUG` so there's no point in calling this function unless this level of logging is enabled (via the `-vvv` cmdline parameter).
We have some indication that this function is problematic in #154 so calling it only when neccessary might help. We also have issues with flaky tests, #163. While the change here does not solve the flakiness (see failures [here](https://github.com/aiidalab/aiidalab-launch/actions/runs/4065691776/jobs/7000768652) and [here](https://github.com/aiidalab/aiidalab-launch/actions/runs/4065691776/jobs/7000768652)), it does seem to help since the test suite no longer times out, …
> Call echo_logs only when in DEBUG mode

- aiidalab_launch/__main__.py
A companion to the same PR at the `aiidalab` package.
https://github.com/aiidalab/aiidalab/pull/369
> CLI: Add -h option as an alias for --help

- README.md
- aiidalab_launch/__main__.py
- tests/test_cli.py
fixes #175 
Remember to update the aiidalab doc https://github.com/aiidalab/aiidalab/pull/385
> CLI: change profiles to profile to align with verdi

- tests/test_cli.py
The new test added in #181 is failing after merging to master since we changes `profiles` to `profile`.
> Fix new profile test

- aiidalab_launch/__main__.py
fixes #179 
The `pull` option was set as the default that will cause to download latest version when it is available, which is not desired as discussed in #179. In most case, user want to keep on using the image they pulled in the first place. New version image download is better happened when explicitly triggered by setting `pull`. 
This commit first to make `--no-pull` the default of `--pull/no-pull` option. The pull logic tweaks a bit that when the image does not exist, it will anyway trigger the pull. If the image exists, the `--pull` need to be set to trigger the pull.
> Trigger pull explictly if needed

- .github/workflows/ci.yml
- .github/workflows/release.yml
- setup.cfg
The blocker here was the `docker` Python API dependency, old version relied on `distutils` package that was removed in Python 3.12. I also took this opportunity to upgrade test dependencies and some Github actions.
Closes #194
> Support Python 3.12

- aiidalab_launch/profile.py
flake8 currently fails on main (I have no idea why the CI is green on the latest commit though, very strange). This is the error:
```python
aiidalab_launch/profile.py:94:17: B038 editing a loop's mutable iterable often leads to unexpected results/bugs
self.extra_mounts.remove(extra_mount)
```
> Fix flake8 violation

- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
- setup.cfg
Main goal here is to upgrade to `docker-py==7.0.0` which contains a bugfix that I ran into while testing locally with Python 3.12:
https://github.com/docker/docker-py/issues/3151
Looks like the bug was introduced in version `6.2` which we bumped to in #194 but did not release yet so no users should be affected. 
Depends on #201
> Update dependencies: docker -> 7.0.0 and tabulate -> 0.9.0

- .github/workflows/ci.yml
- README.md
- aiidalab_launch/profile.py
- setup.cfg
- tests/conftest.py
Podman seems to work out-of-a-box with a little extra setup. I've also tweaked the `DEFAULT_IMAGE` to include the `docker.io/` prefix since that might not be default for Podman.
Closes #196
> Support Podman

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- aiidalab_launch/__main__.py
- aiidalab_launch/util.py
- pyproject.toml
- setup.cfg
- tests/test_cli.py
aiida-core recently switched to ruff, and I've been using it for my app for some time. IMO we should consider slowly switching AiiDAlab repos as well. @unkcpz @yakutovicha LMK what you think. 
I've enabled a couple more rules than there were before, based on my judgment and previous experience. More might be useful, but this is a reasonable start IMO.
I've also removed a couple of hooks that did not seem as useful, now that the codebase and its configuration is quite stable. But I am happy to revert.
> Use ruff instead of flake8, isort, black and pyupgrade
